In [2]:
from scraper.grid_builder import GridBuilder
from grid_manager import GRID_INDICES
import numpy as np
from scraper.graph_loader import GraphLoader
from scraper.geometry_processor import GeometryProcessor

### Download mesh and get grid from OSM

#### Current version

In [4]:
cityname = "Kraków"

loader = GraphLoader()

graph = loader.load_graph(cityname)

edges = loader.get_edges_measurements(graph)

gdf_edges = loader.convert_to_gdf(edges)

geometry_processor = GeometryProcessor()
gdf_edges["geometry"] = gdf_edges.apply(lambda row: geometry_processor.get_edge_polygon(row), axis=1)

# np_streets = get_city_grid(f"{cityname}, Poland")
# print("generating altitudes")
# np_altitudes = np.zeros(np_streets.shape, dtype=np.float64) - 10
# print("concatenating")
# grid = np.concat(
#     [
#         np_streets[:, :, np.newaxis],
#         np_altitudes[:, :, np.newaxis]
#     ],
#     2
# )
# write(grid, cityname)
# print(f"wymiary siatki punktów: {grid.shape}")
# print(f"punkt (100, 200): droga {grid[100, 200, GRID_INDICES.IS_STREET_INDEX]}, wysokość: {grid[100, 200, GRID_INDICES.ALTITUDE_INDEX]}")

Roads with 'width' attribute: 8480
Roads without 'width' attribute: 12782


In [6]:
gdf_edges.total_bounds

array([557007.99355308, 234163.2535988 , 586502.23656834, 250801.29040552])

### Data management

In [1]:
from grid_manager import GridManager
import numpy as np

filename = "test2.dat"

man = GridManager(filename, 2000, 2000, 0.0, 0.0, 1, 3, 3)

a = np.zeros((2000, 2000, 2), dtype=np.float64)
man.write_segment(a[:2,:3, :] + 1, 666, 0)
man.write_segment(a[:3,:2, :] + 2, 0, 666)

print(f"1: {man.read_segment(666, 0)}")
print(f"2: {man.read_segment(0, 666)}")

print(man.get_metadata())


1: [[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
2: [[[2. 2.]
  [2. 2.]]

 [[2. 2.]
  [2. 2.]]

 [[2. 2.]
  [2. 2.]]]
GridFileMetadata(version=1, rows_number=2000, columns_number=2000, upper_left_longitude=0.0, upper_left_latitude=0.0, grid_density=1.0, segment_h=3, segment_w=3, byteorder='little', metadata_bytes=33)
